#!/usr/bin/env ruby
require 'thor'
require 'esquis'

module Esquis
  class Cli < Thor
    desc "compile FILE", "compile and run esquis script"
    def compile(es_path)
      ll_path = if es_path.end_with?(".es")
                  es_path.sub(/\.es\z/, ".ll")
                else
                  es_path + ".ll"
                end
      ll = Esquis.compile(File.read(es_path))
      File.write(ll_path, ll)
      return ll_path
    end

    desc "exec FILE", "compile and run esquis script"
    def exec(es_path)
      ll_path = compile(es_path)
      system "lli", ll_path
    end
  end
end

Esquis::Cli.start(ARGV)
