#!/usr/bin/env ruby
require 'thor'
require 'esquis'

module Esquis
  class Cli < Thor
    desc "compile FILE", "compile esquis script into .ll"
    def compile(es_path)
      ll_path = if es_path.end_with?(".es")
                  es_path.sub(/\.es\z/, ".ll")
                else
                  es_path + ".ll"
                end
      ll = Esquis.compile(File.read(es_path))
      File.write(ll_path, ll)
      return ll_path
    end

    option "keep_files", type: :boolean, default: false, desc: "keep intermediate files"
    desc "exec FILE", "compile and run esquis script"
    def exec(es_path)
      Esquis.run(File.read(es_path),
                 src_path: options[:keep_files] ? es_path : nil)
    end
  end
end

Esquis::Cli.start(ARGV)
